const { v4: uuidv4 } = require('uuid');

const productImages = {
  indian: [
    'https://images.unsplash.com/photo-1600430665436-d4ff685937eb',
    'https://images.unsplash.com/photo-1611140606588-dd052558ffb8',
  ],
  western: [
    'https://images.unsplash.com/photo-1571222787436-74868e84af34',
    'https://images.unsplash.com/photo-1596337635980-8d2243ea07fb',
  ],
  korean: [
    'https://images.unsplash.com/photo-1611351903570-bb4d3499c046',
    'https://images.unsplash.com/photo-1611352110288-9e204ae300bb',
  ],
  jeans: [
    'https://images.unsplash.com/photo-1578067119116-dc7ca1dd23ff',
    'https://images.unsplash.com/photo-1588371995259-c69a24964e5d',
    'https://images.unsplash.com/photo-1564498659566-cc4eccb7d6bb',
  ],
  tops: [
    'https://images.unsplash.com/photo-1578901787297-6ee2f54334fd',
    'https://images.unsplash.com/photo-1615153921046-47af653d6e11',
    'https://images.unsplash.com/photo-1568323304157-ffff8024aaab',
  ],
};

const products = [
  // Indian Wear
  {
    id: uuidv4(),
    name: 'Elegant Silk Saree',
    description: 'Beautiful silk saree with intricate embroidery perfect for special occasions',
    price: 4999,
    salePrice: 4999,
    category: 'indian',
    image: productImages.indian[0],
    images: [productImages.indian[0]],
    sizes: ['Free Size'],
    discount: 0,
    featured: true,
    isNew: true,
    stock: 50,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Traditional Anarkali Suit',
    description: 'Stunning anarkali with beautiful work and dupatta',
    price: 3499,
    salePrice: 2799,
    category: 'indian',
    image: productImages.indian[1],
    images: [productImages.indian[1]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 20,
    featured: true,
    isNew: false,
    stock: 40,
    createdAt: new Date(),
  },
  // Western Wear
  {
    id: uuidv4(),
    name: 'Classic Black Blazer',
    description: 'Professional black blazer perfect for office and formal events',
    price: 2999,
    salePrice: 2999,
    category: 'western',
    image: productImages.western[0],
    images: [productImages.western[0]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 0,
    featured: true,
    isNew: true,
    stock: 60,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Elegant White Shirt',
    description: 'Minimalist white shirt for a clean, professional look',
    price: 1499,
    salePrice: 1199,
    category: 'western',
    image: productImages.western[1],
    images: [productImages.western[1]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 20,
    featured: false,
    isNew: false,
    stock: 80,
    createdAt: new Date(),
  },
  // Korean Fashion
  {
    id: uuidv4(),
    name: 'Korean Style Leather Jacket',
    description: 'Trendy black leather jacket inspired by K-fashion',
    price: 3999,
    salePrice: 2999,
    category: 'korean',
    image: productImages.korean[0],
    images: [productImages.korean[0]],
    sizes: ['S', 'M', 'L'],
    discount: 25,
    featured: true,
    isNew: true,
    stock: 30,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Chic Black Korean Outfit',
    description: 'Modern Korean style outfit perfect for casual outings',
    price: 2799,
    salePrice: 2799,
    category: 'korean',
    image: productImages.korean[1],
    images: [productImages.korean[1]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 0,
    featured: true,
    isNew: false,
    stock: 45,
    createdAt: new Date(),
  },
  // Jeans
  {
    id: uuidv4(),
    name: 'Classic Black Jeans',
    description: 'Comfortable black jeans with perfect fit',
    price: 1999,
    salePrice: 1599,
    category: 'jeans',
    image: productImages.jeans[0],
    images: [productImages.jeans[0]],
    sizes: ['26', '28', '30', '32', '34'],
    discount: 20,
    featured: true,
    isNew: false,
    stock: 100,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Denim Jacket',
    description: 'Stylish denim jacket for a trendy look',
    price: 2499,
    salePrice: 2499,
    category: 'jeans',
    image: productImages.jeans[1],
    images: [productImages.jeans[1]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 0,
    featured: false,
    isNew: true,
    stock: 55,
    createdAt: new Date(),
  },
  // Tops
  {
    id: uuidv4(),
    name: 'Blue Casual Shirt',
    description: 'Comfortable blue shirt perfect for everyday wear',
    price: 1299,
    salePrice: 999,
    category: 'tops',
    image: productImages.tops[0],
    images: [productImages.tops[0]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 23,
    featured: false,
    isNew: false,
    stock: 90,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Polka Dot Top',
    description: 'Fun and stylish polka dot top',
    price: 1199,
    salePrice: 1199,
    category: 'tops',
    image: productImages.tops[1],
    images: [productImages.tops[1]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 0,
    featured: true,
    isNew: true,
    stock: 70,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Elegant Black Top',
    description: 'Sophisticated black top for any occasion',
    price: 1599,
    salePrice: 1599,
    category: 'tops',
    image: productImages.tops[2],
    images: [productImages.tops[2]],
    sizes: ['S', 'M', 'L', 'XL'],
    discount: 0,
    featured: false,
    isNew: false,
    stock: 65,
    createdAt: new Date(),
  },
];

async function seedProducts() {
  try {
    const response = await fetch('http://localhost:3000/api/seed/products', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ products }),
    });

    const data = await response.json();
    console.log('Seed result:', data);
  } catch (error) {
    console.error('Seed error:', error);
  }
}

seedProducts();
